config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :loans do
    collection do
      get :loan
    end
  end

  resources :inventories

  resources :staffs

  resources :customers

  resources :showrooms

  root 'showrooms#index'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :quotes
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:fname, :lname)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :First_Name %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :Last_Name %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Editing Staff Member</h2>
  <%= link_to 'Show', @staff %> |
  <%= link_to 'Back', staffs_path %>
</div>

<%= render 'form' %>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/staffs/index.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Manage Employees</h2>
  <%= link_to 'Enter New Staff Member', new_staff_path %>
</div>

<div id="article">

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.fname %></td>
        <td><%= staff.lname %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <br>

</div>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/staffs/new.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes & Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Entering New Staff Member</h2>
  <%= link_to 'Back', staffs_path %>
</div>

<%= render 'form' %>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/staffs/show.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Showing Staff Member Detail</h2>
  <%= link_to 'Edit', edit_staff_path(@staff) %> |
  <%= link_to 'Back', staffs_path %>
</div>

<div id="article">

<p>
  <strong>First Name:</strong>
  <%= @staff.fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @staff.lname %>
</p>

</div>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>