config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :loans do
    collection do
      get :loan
    end
  end

  resources :inventories

  resources :staffs

  resources :customers

  resources :showrooms

  root 'showrooms#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :inventory
  belongs_to :customer
  belongs_to :staff

  @@markupval=0.10
  @@tax=0.043

  def sold
    if self.status == false
      return "Available"
    else
      return "Sold"
    end
  end
  def marked
    mark = (base * @@markupval)
    return mark
  end

  def markedup
    markups = (base + marked)
    return markups
  end

  def taxtotals
    tax_total = (markedup * @@tax)
    return tax_total
  end

  def total
    final = ((markedup + taxtotals))
    return final
  end

  def self.grandrevenue
    gross=0
    Quote.all.each do |counter|
      if counter.status == true
        gross += counter.total
      end
    end
    return gross
  end

  def self.netprofit
    net=0
    Quote.all.each do |money|
      if money.status == true
        net += money.marked
      end
    end
    return net
  end

  def self.taxtotal
    tax=0
    Quote.all.each do |taxes|
      if taxes.status == true
        tax += taxes.taxtotals
      end
    end
    return tax
  end


end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:sale, :base, :markup, :tax, :total, :status, :inventory_id, :staff_id, :customer_id)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
    <% if @quote.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

          <ul>
            <% @quote.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :base %><br>
      <%= f.text_field :base, :value => '150000' %>
    </div>
    <div class="field">
      <%= f.label :markup %><br>
      <%= f.text_field :markup, :value => '15000' %>
    </div>
    <div class="field">
      <%= f.label :tax %><br>
      <%= f.text_field :tax, :value => '7095' %>
    </div>
    <div class="field">
      <%= f.label :total %><br>
      <%= f.text_field :total, :value => 'Calculated' %>
    </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.check_box :status %>
    </div>
    <div class="field">
      <%= f.label :inventory_id %><br>
      <%= f.collection_select :inventory_id, Inventory.all, :id, :color %>
    </div>

    <div class="field">
      <%= f.label :staff_id %><br>
      <%= f.collection_select :staff_id, Staff.all, :id, :lname %>
    </div>
    <div class="field">
      <%= f.label :customer_id %><br>
      <%= f.collection_select :customer_id, Customer.all, :id, :lname %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/quotes/edit.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Editing Quote</h2>
  <%= link_to 'Show', @quote %> |
  <%= link_to 'Back', quotes_path %>
</div>


<%= render 'form' %>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/quotes/index.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Management Sales Reports</h2>
  <%= link_to 'Create New Quote / Finalize Sale', new_quote_path %>
</div>

<div id="article">

<table>
  <thead>
  <th colspan="11">Individual Sales List</th>
  <tr>
    <th>Base Price</th>
    <th>Markup</th>
    <th>Tax</th>
    <th>Total</th>
    <th>Status</th>
    <th>Inventory Item</th>
    <th>Sales Staff</th>
    <th>Customer Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @quotes.each do |quote| %>
      <tr>
        <td><%= number_to_currency(quote.base) %></td>
        <td><%= number_to_currency(quote.markup) %></td>
        <td><%= number_to_currency(quote.tax) %></td>
        <td><%= number_to_currency(quote.total) %></td>
        <td><%= quote.sold %></td>
        <td><%= quote.inventory.color %></td>
        <td><%= quote.staff.lname %></td>
        <td><%= quote.customer.lname%></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
  <br>
<table>
  <thead>
  <th colspan="3">Owner Summary Report</th>
    <tr>
      <th>Total Gross Revenue</th>
      <th>Sales Tax Total</th>
      <th>Net Profit</th>
    </tr>

  </thead>

  <tbody>
    <tr>
      <td> <%= number_to_currency(Quote.grandrevenue, :unit => "$", :delimeter => ".") %></td>
      <td> <%= number_to_currency(Quote.taxtotal, :unit => "$", :delimeter => ".") %></td>
      <td> <%= number_to_currency(Quote.netprofit, :unit => "$", :delimeter => ".") %></td>
    </tr>
  </tbody>
</table>

</div>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/quotes/new.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes & Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Creating New Quote / Finalizing Sale</h2>
  <%= link_to 'Back', quotes_path %>
</div>

<%= render 'form' %>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/quotes/show.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Showing Quote Detail</h2>
  <%= link_to 'Edit', edit_quote_path(@quote) %> |
  <%= link_to 'Back', quotes_path %>
</div>

<div id="article">

<p>
  <strong>Base:</strong>
  <%= number_to_currency(@quote.base) %>
</p>

<p>
  <strong>Markup:</strong>
  <%= number_to_currency(@quote.markup) %>
</p>

<p>
  <strong>Tax:</strong>
  <%= number_to_currency(@quote.tax) %>
</p>

<p>
  <strong>Total:</strong>
  <%= number_to_currency(@quote.total) %>
</p>

<p>
  <strong>Sold Status:</strong>
  <%= @quote.status %>
</p>

<p>
  <strong>Inventory ID:</strong>
  <%= @quote.inventory_id %>
</p>

<p>
  <strong>Staff ID:</strong>
  <%= @quote.staff_id %>
</p>

<p>
  <strong>Customer ID:</strong>
  <%= @quote.customer_id %>
</p>

</div>


<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>