config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :loans do
    collection do
      get :loan
    end
  end

  resources :inventories

  resources :staffs

  resources :customers

  resources :showrooms

  root 'showrooms#index'

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_one :quote
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:make, :model, :year, :color, :vin)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes & Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Editing Inventory Item</h2>
  <%= link_to 'Show', @inventory %> |
  <%= link_to 'Back', inventories_path %>
</div>


<%= render 'form' %>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/inventories/index.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes & Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>View / Manage Inventory</h2>
  <%= link_to 'Enter New Inventory Item', new_inventory_path %>
</div>

<div id="article">

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Color</th>
      <th>Vin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.make %></td>
        <td><%= inventory.model %></td>
        <td><%= inventory.year %></td>
        <td><%= inventory.color %></td>
        <td><%= inventory.vin %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/inventories/new.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes & Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Entering New Inventory Item</h2>
  <%= link_to 'Back', inventories_path %>
</div>

<%= render 'form' %>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/inventories/show.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Showing Inventory Item Detail</h2>
  <%= link_to 'Edit', edit_inventory_path(@inventory) %> |
  <%= link_to 'Back', inventories_path %>
</div>

<div id="article">
<p>
  <strong>Make:</strong>
  <%= @inventory.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @inventory.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @inventory.year %>
</p>

<p>
  <strong>Color:</strong>
  <%= @inventory.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @inventory.vin %>
</p>

</div>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>