config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :loans do
    collection do
      get :loan
    end
  end

  resources :inventories

  resources :staffs

  resources :customers

  resources :showrooms

  root 'showrooms#index'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  def self.payment
    @@payment
  end

  def self.interest_paid
    @@interest_paid
  end

  def self.principal_paid
    @@principal_paid
  end

  def amort_table
    return self.class.amort_table(self.price, self.irate, self.term)
  end

  def self.amort_table(price = 0.00, irate = 0.00, term = 0)
    Rails.logger.debug "Inputs: #{price} #{irate} #{term}"
    loan = []
    fixed = price
    (1..term*12).each do |counter|
      term_rate = irate/12
      @@payment = ((term_rate*fixed)/(1-(1+term_rate)**(-term*12)))
      loan << price - (@@payment - (price*irate))

      last = price - (@@payment - (price*term_rate))

      price = last

      @@interest_paid = (irate) * @@payment
      @@principal_paid = (@@payment-@@interest_paid)
    end
    return loan
  end

  end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  def loan
    price =params[:price]
    irate=params[:irate]
    term=params[:term]
    @loan_array = Loan.amort_table(price.to_d, irate.to_d, term.to_i)
  end

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
    @loan_array = @loan.amort_table
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_loan
    @loan = Loan.find(params[:id])
  end

  def loan_params
    params.require(:loan).permit(:price, :irate, :term)
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
    <% if @loan.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

          <ul>
            <% @loan.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :"term:_3,_4,_or_5_Years" %><br>
      <%= f.number_field :term, :value => '3, 4, or 5 years' %>
    </div>
    <div class="field">
      <%= f.label :amount_Financed %><br>
      <%= f.text_field :price, :value => '172095.' %>
    </div>
    <div class="field">
      <%= f.label :interest_Rate %><br>
      <%= f.text_field :irate, :value => '.0429' %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<div id = "loan_table" class = "table-format"></div>

app/views/loans/_loan.erb
<table class="CSSTableGenerator" width="30%">
  <th>Payment #</th>
  <th>Balance Remaining</th>
  <th>Payment Amount</th>
  <th>Payment Principal</th>
  <th>Payment Interest</th>

  <%counter=0%>
  <% @loan_array.each_with_index do |p,n|  %>
      <tr>
        <td><%= n+1 %></td>
        <td><%= number_to_currency(p.round(2)) %></td>
        <td><%= number_to_currency(Loan.payment.round(2)) %></td>
        <td><%= number_to_currency(Loan.principal_paid.round(2))%></td>
        <td><%= number_to_currency(Loan.interest_paid.round(2))%></td>
      </tr>
      <%counter+=1%>
  <% end %>

</table>

app/views/loans/edit.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Editing Loan</h2>
  <%= link_to 'Show', @loan %> |
  <%= link_to 'Back', loans_path %>
</div>

<%= render 'form' %>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/loans/index.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Loan Management</h2>
  <%= link_to 'Calculate New Loan', new_loan_path %>
</div>

<div id="article">

<table>
  <thead>
  <tr>
    <th>Term in Years</th>
    <th>Amount Financed</th>
    <th>Interest Rate</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.term %></td>
        <td><%= number_to_currency(loan.price) %></td>
        <td><%= number_to_percentage(loan.irate * 100, precision: 1) %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

</div>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/loans/loan.js.erb
$('#loan_table').html("<%= j (render 'loan') %>")

app/views/loans/new.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Calculating New Loan</h2>
  <%= link_to 'Back', loans_path %>
</div>

<div id="article">

<%= render 'form' %>

</div>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>

app/views/loans/show.html.erb
#encoding: UTF-8

<div id="header">
  <h1>Beachnight Automotives</h1>
  <h3>Twin engine Dune Buggies for the 21st Century</h3>
</div>

<div id="nav">
  <table border="1" style="width:100%">
    <tr>
      <th colspan="5">Navigation</th>
    </tr>
    <tbody>
    <tr>
      <td>Showroom</td>
      <td>Sales Staff</td>
      <td>Finance Manager</td>
      <td>Inventory Manager</td>
      <td>Sales Manager / Owner</td>
    </tr>
    <tr>
      <td><%= link_to 'Meet the 2003', showrooms_path %><br><%= link_to 'Peugeot Hoggar', showrooms_path %></td>
      <td><%= link_to 'Search / Manage Customers', customers_path %><br><%= link_to 'View Inventory', inventories_path %><br><%= link_to 'View Quotes / Finalize Sales', quotes_path %></td>
      <td><%= link_to 'Show breakdown of interest and', loans_path %><br><%= link_to 'principal for all loan payments', loans_path %></td>
      <td><%= link_to 'Manage Inventory', inventories_path %></td>
      <td><%= link_to 'Manage Employees', staffs_path %><br><%= link_to 'Management Sales Reports', quotes_path %></td>
    </tr>
    </tbody>
  </table>
</div>

<div id="aside">
  <h2>Showing Loan Detail</h2>
  <%= link_to 'Edit', edit_loan_path(@loan) %> |
  <%= link_to 'Back', loans_path %>
</div>

<div id="article">
  <table>
    <thead>
      <tr>
      <th>Term in Years:</th>
      <th>Purchase Price:</th>
      <th>Interest Rate:</th>
    </tr>
    </thead>

    <tbody>
    <tr>
      <td> <%= @loan.term %></td>
      <td> <%= number_to_currency(@loan.price) %></td>
      <td> <%= number_to_percentage(@loan.irate * 100, precision: 1) %></td>
    </tr>
    </tbody>
  </table>
  <br><br>

  <table class="CSSTableGenerator" width="30%">
    <th>Payment #</th>
    <th>Balance Remaining</th>
    <th>Payment Amount</th>
    <th>Payment Principal</th>
    <th>Payment Interest</th>

    <%counter=0%>
    <% @loan_array.each_with_index do |p,n|  %>
        <tr>
          <td><%= n+1 %></td>
          <td><%= number_to_currency(p.round(2)) %></td>
          <td><%= number_to_currency(Loan.payment.round(2)) %></td>
          <td><%= number_to_currency(Loan.principal_paid.round(2))%></td>
          <td><%= number_to_currency(Loan.interest_paid.round(2))%></td>
        </tr>
        <%counter+=1%>
    <% end %>

  </table>
</div>

<br><br><br><br>
<div id="gallery">
  <h2>Gallery - 2003 Peugeot Hoggar</h2>
  <%= image_tag "PH1.jpg",:size => "300x220", :title => 'Peugeot Hoggar' %>  <%= image_tag "PH2.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH3.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH4.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH6.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH7.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH8.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH9.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH10.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH11.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH12.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>  <%= image_tag "PH13.jpg",:size => "300x220",:title => 'Peugeot Hoggar' %>
</div>

<div id="footer">
  <h5 class="copyright">Created by: <a href="mailto:jwcarter2@uh.edu">James Carter</a>.  CIS4339 - Enterprise Applications Development.  Instructor: Keith C Lancaster.</h5>
</div>